

export const questions: string[] = [
    "Dance like a X , sing like a X .",
    "The X in the X jumps over the X .",
    "X is the key to X .",
    "A journey of a thousand X begins with a single X .",
    "X is the spice of X .",
    "X in doubt, X it out.",
    "X by day, X by night.",
    "X is thicker than X .",
    "X the X away.",
    "X in the X , life's a X .",
    "X marks the X .",
    "In the blink of X X .",
    "X and X .",
    "X of the X .",
    "A piece of X X .",
    "Catch X X .",
    "X to the X .",
    "Lost in X X .",
    "Through X and X .",
    "X the X .",
    "X echoes in X .",
    "Chase X with X .",
    "X under the X .",
    "X through the X .",
    "Embrace X with X .",
    "X in the X .",
    "Dance X with X .",
    "X the X path.",
    "Whispers in X X .",
    "X the X journey.",
    "What gives life its meaning for you? X X",
    "What aspects of life spark your deepest sense of wonder? X X X",
    "What's the best cook book you know? X X X",
    "Worst thing about italians? X X X",
    "If i could i would kill a/an X X X",
    "Life is like a box of X .",
    "When the going gets tough, the tough get X .",
    "The early bird catches the X .",
    "You can't have your cake and X it too.",
    "Actions speak louder than X .",
    "Never count on your X X",
    "All that glitters is not X .",
    "Better late than X .",
    "Every cloud has a silver X .",
    "When in Rome, do as the X do.",
    "Honesty is the best X .",
    "Curiosity killed the X .",
    "Two heads are better than X .",
    "A picture is worth a thousand X .",
    "Don't put all your eggs in one X .",
    "When the cat's away, the mice will X .",
    "If the shoe X , wear it.",
    "The grass is always greener on the other X .",
    "Don't bite the hand that X you.",
    "People who live in glass houses shouldn't throw X .",
    "Life is like X , full of surprises and X .",
    "X times call for tough X , keep going.",
    "Early X catches the X and avoids the storm.",
    "Can't X cake and X it too, enjoy the moment.",
    "Actions X louder than X , make them count.",
    "Don't count X before they're X , stay patient.",
    "All that X is not X , cherish authenticity.",
    "Better X than X , embrace the opportunity.",
    "Every X has a X lining, find the positive.",
    "In Rome, do as the X do, immerse in culture.",
    "Honesty is the best X , build trust.",
    "X X killed the X , be cautious.",
    "Two X are better than X , collaboration is key.",
    "A X is worth a X words, capture the essence.",
    "Don't put all your X in one X , diversify.",
    "When the X's away, the mice will X , seize the chance.",
    "If the X fits, X it with style.",
    "The X is always greener on the X side, appreciate what you have.",
    "Don't X the hand that X you, value relationships.",
    "People who live in X houses shouldn't throw X , be mindful.",
]